### ISSUE TITLE
[Feat]: 카테고리 및 메뉴화면 작업

### ISSUE THREAD

**Issue by NeoSelf1** [hamsik22/NBC-W6-Kiosk#2]
- [x] 카테고리
- [x] 메뉴 화면

## 작업 순서
해당 작업에 사용될 기술을 선정합니다.
기술에 대한 공부와 예제코드를 작성합니다.
팀원들의 개발 현황에 따라 본 프로젝트에 코드를 반영합니다.
개발 속도에 맞춰서 필요한 기능이나 화면은 PR로 반영합니다.

## 작업 환경
KioskViewController.swift에서 작업
MenuItem, MenuCategory 등, 메뉴화면을 구성하는 데에 있어 필요로 하는 열거형 및 구조체 파일 새로 생성 예정
해당 파일들 안에서 UI와 데이터 로직을 간단하게 구현할 예정
추후 병합 과정에서 로직을 수정할 계획

**Comment by hamsik22** [comment]
@NeoSelf1 
해당 이슈가 마무리되었다면 이슈를 닫아주세요!
추후 작업을 새로운 이슈를 생성해서 작업하면 어떨까요?
